### ISSUE TITLE
Geograph photos aren't https

### ISSUE THREAD

**Issue by jnicho02** [openheritage/open-plaques-3#26]
http://openplaques.org/plaques/5054 tries to show an https Geograph photo but unfortunately they only seem to be http. This will invalidate an https page...what to do?

**Comment by jnicho02** [comment]
Many (all?) Geograph images are copied into Wikimedia Commons. If we use their copy then it is https. A related problem is this duplication of images as Photo is unique keyed on url. We need some magic to match two Photo records and only use one of them

**Comment by edent** [comment]
This is also an issue on the "add a photo" page. 

For example http://openplaques.org/plaques/42552/photos

Tries to load https://www.geograph.org.uk/templates/basic/img/logo.gif

Replacing the `https` with `http` would suffice.

**Comment by jnicho02** [comment]
I believe that they are now serving https
