### ISSUE TITLE
HTML entities in Photographers graph

### ISSUE THREAD

**Issue by edent** [openheritage/open-plaques-3#80]
If a user's name contains `'` it is rendered as the HTML entity `&#39;`
![html](https://cloud.githubusercontent.com/assets/837136/24347782/6b2b9f52-12d1-11e7-9254-fed63cae5a68.png)

Suspect this is the culprit: https://github.com/openheritage/open-plaques-3/blob/master/app/views/photographers/index.html.erb#L26

        hbar.Set('chart.labels', [<% @photographers.each_with_index do |photographer, idx| %><% if idx < 50 %>'<%= photographer.id %>',<% end %><% end %>]);

**Comment by jnicho02** [comment]
Ironically, one of them is me. I am J'Roo (short for 'Jez-eroo' on Flickr)

**Comment by edent** [comment]
I'm just annoyed that my contributions aren't on there yet 😉

**Comment by jnicho02** [comment]
should be fixed now
