### ISSUE TITLE
Broken https links on OpenStreetMap

### ISSUE THREAD

**Issue by edent** [openheritage/open-plaques-3#89]
1. Visit http://openplaques.org/places/gb/areas/oxford/plaques
1. Click on a blue dot
1. Click on the plaque ID
1. Browser error due to insecure connection

![screen shot 2017-06-08 at 15 14 23](https://user-images.githubusercontent.com/837136/26933274-000f09cc-4c5e-11e7-84fd-1a7ccd624f73.png)

Problem seems to be caused by this JS insisting on `https`

https://github.com/openheritage/open-plaques-3/blob/master/app/assets/javascripts/plaque-map.js#L41

Should be `http:` until the site supports https.

**Comment by jnicho02** [comment]
Hmmm...site did support https...something must have changed with the cert

**Comment by edent** [comment]
I'm seeing

> The certificate is only valid for the following names: *.herokuapp.com, herokuapp.com

https://www.ssllabs.com/ssltest/analyze.html?d=openplaques.org
